---
name: nightly
on:
# currently a manual snapshot release build instead of a nightly,
#  as I haven't figured out yet how to prevent spamming the releases with no changes at all.
#  schedule:
    # * is a special character in YAML, so you have to quote this string
    # doing builds Tue-Sat, so we have changes from Fri
    # available already on Sat
#    - cron:  '0 0 * * *'
  workflow_dispatch:
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}