---
name: release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version: 1.22
    - name: Print go version
      run: go version
    - name: Run unit tests
      run: go test -cover ./...
    - name: Run goreleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# disable krew install for now as this would conflict with the original. I'd have to rename the project to do this safely.
#    - name: Update new version in krew-index
#      uses: rajatjindal/krew-release-bot@v0.0.40
